class ProductConstants:
    CSV_CHUNK_SIZE = 2000
    CSV_MAX_FILE_SIZE = 100 * 1024 * 1024
    CSV_ALLOWED_EXTENSIONS = ['.csv']
    PROGRESS_UPDATE_INTERVAL = 1000
    PROGRESS_UPDATE_TIME_INTERVAL = 2
    SKU_MAX_LENGTH = 255
    SKU_MIN_LENGTH = 1
    PRODUCT_NAME_MAX_LENGTH = 500
    DESCRIPTION_MAX_LENGTH = 5000


class WebhookConstants:
    WEBHOOK_URL_MAX_LENGTH = 500
    EVENT_TYPE_MAX_LENGTH = 50
    SECRET_MAX_LENGTH = 255
    WEBHOOK_MAX_RETRIES = 3
    WEBHOOK_RETRY_DELAY = 5
    WEBHOOK_TIMEOUT = 10


class ImportJobConstants:
    STATUS_MAX_LENGTH = 20
    FILE_NAME_MAX_LENGTH = 255
    PROGRESS_MIN = 0
    PROGRESS_MAX = 100
