# Generated by Django 4.2.23 on 2025-11-29 05:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.IntegerField(choices=[(0, 'ACTIVE'), (1, 'INACTIVE')], db_index=True, default=0)),
                ('url', models.URLField(max_length=500)),
                ('event_type', models.CharField(choices=[('product.created', 'Product Created'), ('product.updated', 'Product Updated'), ('product.deleted', 'Product Deleted'), ('import.completed', 'Import Completed'), ('import.failed', 'Import Failed')], max_length=50)),
                ('secret', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'webhooks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state', 'event_type'], name='webhooks_state_cf188a_idx')],
                'unique_together': {('url', 'event_type')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.IntegerField(choices=[(0, 'ACTIVE'), (1, 'INACTIVE')], db_index=True, default=0)),
                ('sku', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sku'], name='products_sku_fe2039_idx'), models.Index(fields=['state'], name='products_state_203c77_idx'), models.Index(fields=['name'], name='products_name_6f9890_idx'), models.Index(fields=['state', 'created_at'], name='products_state_7ca934_idx'), models.Index(fields=['state', 'name'], name='products_state_1bf5b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.IntegerField(choices=[(0, 'ACTIVE'), (1, 'INACTIVE')], db_index=True, default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('total_records', models.IntegerField(default=0)),
                ('processed_records', models.IntegerField(default=0)),
                ('successful_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'import_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='import_jobs_status_46b7f9_idx'), models.Index(fields=['created_at'], name='import_jobs_created_139a66_idx'), models.Index(fields=['state'], name='import_jobs_state_0e0676_idx'), models.Index(fields=['status', 'created_at'], name='import_jobs_status_aedc42_idx'), models.Index(fields=['state', 'created_at'], name='import_jobs_state_30be56_idx')],
            },
        ),
    ]
